version: '3.7'

services:
  api:
    build:
      context: .
    container_name: cricket-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - db
    volumes:
      - .:/code
    networks:
      - backend
  
  mongodb:
    image: mongo:latest
    container_name: cricket-mongodb
    restart: always
    command: mongod
    env_file: 
      - .env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
    #   MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
    #   MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE:?err}"
    ports:
      - 27017:27017
    volumes:
      - cricket-mongodb:/data/db
    networks:
      - backend

  db:
    image: postgres
    container_name: cricket-pg
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # PGDATA
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "cricket-pg-data:/var/lib/postgresql/data"
    networks:
      - backend

volumes:
  cricket-mongodb:
  cricket-pg-data:

networks:
  backend: